[workspace]
members = ["crates/*", "xtask", "vendor/crossterm"]
resolver = "2"
default-members = ["crates/tau-host"]

[patch.crates-io]
tau = { path = "crates/tau" }
crossterm = { path = "vendor/crossterm" }

[profile.release]
debug = true
