[package]
name = "tau"
version = "0.1.0"
edition = "2021"
description = "Tau plugin SDK â€” statically compiled into each plugin"

[lib]
crate-type = ["rlib"]

[dependencies]
tau-rt = { path = "../tau-rt" }
