[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "prefer-dynamic",
    "-C",
    "link-args=-Wl,-undefined,dynamic_lookup",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C",
    "prefer-dynamic",
    "-C",
    "link-args=-Wl,-undefined,dynamic_lookup",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C",
    "prefer-dynamic",
    "-C",
    "link-args=-Wl,--allow-shlib-undefined",
]
