[package]
name = "tokio-test-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tau = { path = "../tau" }
tokio = { version = "1", features = ["time", "sync"] }

[workspace]
